### ISSUE TITLE
Insecure cookie

### ISSUE THREAD

**Issue by magarto** [seblucas/cops#250]
Hi,

There is a security issue with cookie, it is in plain text due to it does not include "secure" flag. Some users use HTTPS (SSL) encryption so it should include it.

It can be fixed adding the following to the header (index.php):

// Uses a secure connection (HTTPS) if possible
ini_set('session.cookie_secure', 1);

Also, I recommend adding also:

// **PREVENTING SESSION HIJACKING**
// Prevents javascript XSS attacks aimed to steal the session ID
ini_set('session.cookie_httponly', 1);

// **PREVENTING SESSION FIXATION**
// Session ID cannot be passed through URLs
ini_set('session.use_only_cookies', 1);

**Comment by seblucas** [comment]
Hi,

Thanks for the security notice. Honestly I never thought I needed that because I honestly thought there was nothing relevant to secure. Looking at it again, the only thing that may be a problem is the email address but that's not a big leak.

Nevertheless, I can't directly add `ini_set('session.cookie_secure', 1);` because it will need no cookies for those who are not using HTTPS (so huge regression).

For the two other recommendations, COPS will only create sessions if `$config ['cops_fetch_protect'] == "1"`, so only for some users of Sony PRS-TX. But you're right that might be useful

I'd gladly accept a patch adding `ini_set('session.cookie_httponly', 1);` but this PR has to include a check for disabled function (ini_set is often disabled with shared hosting).
