### ISSUE TITLE
Error in Kybook (iPhone) - wrong Content-Type

### ISSUE THREAD

**Issue by kotliary** [seblucas/cops#259]
When opening my catalog in Kybook I get the error:
OPDS catalog returned a wrong Content-Type 'text/html;charset=utf-8'
I can browse the books but cannot download any. After attempting it, the program hang up and I had to restart it.
It works using the default browser on the phone. Also works great on android and Windows with any browser I've tried.

COPS 1.0.0RC2 installed as synocommunity package on Synology NAT with DSM 5.2-5644 Update 5.
Kybook ver. 2.0.7 (2070)

**Comment by seblucas** [comment]
Hi,

Did you use feed.php or index.php ?

Honestly I've never heard of Kybook before and I never tested it (IOS app isn't it ?)

**Comment by kotliary** [comment]
Thanks for replying.

I'm not a PHP developer and I'm not sure what I use. I basically installed the synocommunity's package and it worked fluently. How can I find out if I use feed.php or index.php? I have both files in the COPS's directory.

The KyBook is IMHO one of the best e-book readers for iOS, and it's free: http://kolyvan.com/kybook/
I could contact with developers but it would be good at least to understand if it's their bug or from COPS.

Thanks

**Comment by horus68** [comment]
In order to an app to browse your library it requires an URL for the OPDS feed (so it can browse the library).
The URL should be your library URL ending by /feed.php 

If you want to try it, you can use this URL in your favourite OPDS client :
http://cops-demo.slucas.fr/feed.php

Or you can also use any browser:
http://cops-demo.slucas.fr/index.php

Noote: some apps are already configured on COPS to not require that extra /feed.php in URL but it requires to know your app HTTP_USER_AGENT

See also:
OPDS reader identification · Issue #236 · seblucas/cops - https://github.com/seblucas/cops/issues/236

Note: you could try to test your library URL here:
http://opds-validator.appspot.com/

Note to further tests:
URL Rewrite is enabled in your config file?

**Comment by kotliary** [comment]
Yes, it works with feed.php! But not with index.php when I get the same behavior as before.
Thanks a lot for the help!

BTW, FBReader and Moon+ Reader on Android work with index.php as well.

**Comment by horus68** [comment]
Hi the actual list that work is listed in the file index.php near line 23
https://github.com/seblucas/cops/blob/master/index.php
:
`
if (preg_match("/(MantanoReader|FBReader|Stanza|Marvin|Aldiko|Moon+ Reader|Chunky|AlReader|org.ebookdroid)/", `
