### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by new-kirte** [seblucas/cops#261]
Dear Seblucas,
I've installed COPS package on the Synology NAS running DSM 6.0-7321. I've installed Web Station package and PHP 5.6 package.
The calibre library is in /volume1/Library/MainLibrary/ folder. The Web Station is configured as per attached screenshot (web station.jpg). The COPS shows error  - database error (see attached screenshot - COPS error.jpg).
The permissions are assigned as follows (library.jpg and mainlibrary.jpg)
[cops.zip](https://github.com/seblucas/cops/files/214323/cops.zip)

**Comment by guill69f** [comment]
Hi, not bringing any solution (sorry for that), but i have a similar issue, so i just tag along :-) I had COPS (and also BicBucStriim) installed on Synology NAS with DSM, everyting worked fine, but after upgrade to DSM 6 COPS is no longer working.
Likewise, I have webstation and PHP 5.6. I have modified open_dir and all my ebooks and calibre database have rwx permissions...
Not sure where to look now...

**Comment by seblucas** [comment]
Not helping also, But I updated my own DSM and I have the same problem. I did not spend a lot of time on it but it seems strange, You best bet is to ask someone on SynoCommunity, they should have more information about that.

**Comment by vbrett** [comment]
Hello, unfortunately I'm in the exact same situation. I haven't found any clue on synology forum. Any progress on your side? 

Thanks in advance

**Comment by guill69f** [comment]
Hi, no sorry; i haven't gotten much further, except i found no related readings on Synology forums, but I haven't had much time for that

**Comment by bvdbvd** [comment]
I had this issue. Calibre on shared volume Calibre -> /volume1/Calibre/.. After changing to calibre -> /volume1/calibre (mind the lowercase) COPS worked again. Not sure why.

**Comment by vbrett** [comment]
ok, so... i finally solved my issue - thanks to bvdbvd.
Well, actually, it is more a workaround rather than a real soultion.

My Calibre folder was a shared folder called "Calibrary" (mind the uppercase)
I also was properly setting the 2 paths (meaning with correct case and trailing "/"):
- 'calibre_directory' in config_local.php
- 'open_base_dir' in webstation settings

but during the "Check if Calibre database file exists and is readable" in checkconfig.php, the is_readable function was returning an error, considering that the library was not in the allowed paths, these paths were indicated as
"web/cops/" and also "/volume1/calibrary/"  <- mind the lowercase

For some reason, the is_readable was forcing all paths to lower case, leading the issue

I hope that this can help seblucas to find an official solution
As for now, the workaround is to define your library path using only lowercases


Thanks bvdbvd

**Comment by guill69f** [comment]
Hi, did the changes proposed as per the work around above, unfortunately no luck
open_dir is set correctly, calibre metadata.db has correct rights and pernissions etc. 

But the configuration check keeps reporting "database error" and "ile /volume1/calibre/metadata.db not found, Please check". not sure what to do know, will wait and see if there is a fix coming in the future. thanks anyhow

**Comment by seblucas** [comment]
@vbrett 

on my nas my calibre library path is in lower case only and that does not seem to work. I'll check again but I don't think it's a valid fix for all cases.

Thanks anyway for taking the time to report here ;)

**Comment by Sleprek** [comment]
I'm struggling quite a while now to get COPS working again on my Synology NAS after the updates (Don't know if it is DSM 6 or a package update). Checked a thousand times the settings (HTTP rights, Open_base_dir, etc). I have read several forums but no solution or work around found. The capitals or lower case solution from above didn't work for me...

Getting desperate! Somebody found something? Or do we have to wait for an update?

**Comment by seblucas** [comment]
It seems to work (reported by 2 users) see #277
