### ISSUE TITLE
Case-sensitive search

### ISSUE THREAD

**Issue by new-kirte** [seblucas/cops#262]
search in non-English languages (e.g. Russian) is case sensitive.

**Comment by seblucas** [comment]
Hi,

The problem exists with non latin characters (and with some diacritics too), it's due to a limitation of SQLite (check the first paragraph in https://www.sqlite.org/lang_expr.html#like).

I've added a normalized search in #48, it was enhanced by a PR #210 so you can try to add $config ['cops_normalized_search'] = "1"; in config_local.php

But be aware that speed will be way worse.
