### ISSUE TITLE
Support MYSQL instead of SQLITE

### ISSUE THREAD

**Issue by alex9434** [seblucas/cops#270]
Dear all,

Since most PHP installations also have mysql or mariadb installed, could you add support for using mysql/mariadb instead of sylite?

Regards,
Alexander

**Comment by horus68** [comment]
As an user I wish your request is not for a "instead". 
SQlite is good for many scenarios keeping Cops simple to run and easy to maintain.
But I agree that other DB support can be a bonus feature to Cops.
So if someone can add that support I'm ok too!

**Comment by seblucas** [comment]
Sqlite is only used for reading Calibre Database which is only Sqlite.

I don't need any other database so not much hope :(.

**Comment by auspex** [comment]
fwiw, I added 2300 entries to my database a couple of weeks ago, and COPS hasn't worked since. It fails on `PHP Fatal error:  Call to a member function fetchColumn() on boolean in /media/NAS/co
ps/base.php on line 1278, referer: https:...`

Now, the only reference I can find to the same error is actually other websites that are failing, nothing about fixing the problem. I suspect it's a SQLite problem rather than a COPS one, and is one reason for trying to use a MySql db instead. I haven't looked at the DB code for COPS, but I'd hope it's just a matter of changing the database adapter.

**Comment by seblucas** [comment]
Your error should come from your data, I don't think that's SQLite fault.

I have a test Calibre library which has ~ 80000 books and 25000 authors. COPS (and Calibre) works perfectly fine with it.

To reply to your last question, there's not sqlite specific code, only pdo so using a Mysql database should work, adding book and updating it will be harder though.

**Comment by auspex** [comment]
Well, creating a mysql database from a sqlite dump is pretty trivial,
really, so it'll be easy enough to test.  I'll try to do it this week.

derek
