### ISSUE TITLE
create_function() deprecated

### ISSUE THREAD

**Issue by brambil** [seblucas/cops#392]
`Deprecated: Function create_function() is deprecated in /tmp/mnt/NAS/entware/share/www/cops/resources/doT-php/doT.php on line 94`

COPS 1.0.1 

[phpinfo().pdf](https://github.com/seblucas/cops/files/1887244/phpinfo.pdf)

**Comment by seblucas** [comment]
I saw that in the release note for 7.2.0 (around Xmas IIRC). I really don't what to do to replace besides completely changing the templating system. 

I'll think about that.

**Comment by otapi** [comment]
Well, I'm stucked on this :( I want to install COPS to a RT-AC66U_B1 router with Entware-ng. The OPKG pulls only the PHP 7.2 - the older versions are not there. Since the create_function is deprecated in 7.2, the COPS doesn't work anymore. Any workaround on this? Do you know an OPKG repository with older version of PHP?
The newest versions don't seem to help: installing COPS from the master branch Today + copy the vendor folder from the 1.6.5 composer it is even worse with this error message:

> Fatal error: Uncaught Error: Class 'Base' not found in /tmp/mnt/core/entware/share/www/index.php:19 Stack trace: #0 {main} thrown in /tmp/mnt/core/entware/share/www/index.php on line 19 

Please help!

**Comment by seblucas** [comment]
`create_function` should only be used when using server side rendering can you confirm that ?

I've read a lot about alternatives to create_function and did not anything easy to implement

**Comment by seblucas** [comment]
Also the function is deprecated so it still should be working, does it give an error ? I'll check with a docker image soon

**Comment by otapi** [comment]
I don't have the build running anymore as I switched to Calibre-web, sorry!
The orig symptom with COPS latest release and PHP 7.2 was: the browser got the main page with a leading <BR> and an error message about the deprecated function. Followed by the actual page content with <html><head> and so in. It broke all the css and js script on the page and just the raw text of the body were visible without any formatting or style.

**Comment by seblucas** [comment]
Ok thanks I see the problem and will fix it. Thanks a lot for your response

**Comment by brambil** [comment]
> create_function should only be used when using server side rendering can you confirm that ?
The problem is the same, even if with client side rendering.
