### ISSUE TITLE
Some files don't open (not via web or OPDS)

### ISSUE THREAD

**Issue by peroksid5** [seblucas/cops#407]
I have encountered a strange bug with COPS on Synology. Some files won't open in the web interface or via ODPS. Tried on several devices (Kindle, several browsers on different devices, Moon Reader+ on Android). The files are available, can be opened in Calibre or via a direct download (i.e. file manager). Permissions are the same for all files.

Error:
`This site can’t be reached
The web page at http://192.168.2.50/cops/fetch.php?data=8&type=epub&id=5&db=3 might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE`

There's even an instance where the .mobi file works, but the .epub of the same book won't open or download via COPS (and the file is in the same folder, same name).  Changing URL rewriting does nothing - it's the same for the same files.

Has anyone encountered an error like this?

**Comment by seblucas** [comment]
I once had a problem like that, it was due to bad access rigths or lower/upper case problem. Can you check : `http://192.168.2.50/cops/checkconfig.php?full=1`

It can be long but it will check if it can read every file of your library, it will output a list of files with problems. then you can check one file among the list to check the naming and the access rights.
