### ISSUE TITLE
How to change language (not an issue)

### ISSUE THREAD

**Issue by Kimo06** [seblucas/cops#532]
Sorry I m new but i see there are language files but i did not find where to change the english defaukt in the config files

**Comment by Kimo06** [comment]
I Answer my question :
config_default.php
line 398
$config['cops_language'] = 'fr';

**Comment by horus68** [comment]
End of Life (EOL)
The software is no longer maintained by the original (and only) developer since October 2019. Latest version is v.1.1.3. This software repository has no more updates.

New releases
Since July 2023, you can find a forked version that works with PHP8, including some issues fixes and new features, on his personal fork:
[COPS for PHP 8.x] https://github.com/mikespub-org/seblucas-cops
